services:
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example

      MONGODB_USERNAME: 1001
      MONGODB_PASSWORD: 1001
      MONGODB_DATABASE: admin  # ← put 1001 in admin

      MONGODB_EXTRA_USERNAMES: mongo
      MONGODB_EXTRA_PASSWORDS: mongo
      MONGODB_EXTRA_DATABASES: admin  # ← put mongo in admin

    volumes:
      - mongo_data:/bitnami/mongodb


volumes:
  mongo_data: