apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all your base resources
resources:
  - secret-deployment.yaml
  - mongo-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml

# Common labels applied to all resources
#commonLabels:
 # project: expensy


