
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        fsGroup: 1001   # ‚Üê add it here
      containers:
        - name: mongo
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_root_user
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_root_password
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_1001_user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_1001_password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_1001_database
            - name: MONGODB_EXTRA_USERNAMES
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_extra_user
            - name: MONGODB_EXTRA_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_extra_password
            - name: MONGODB_EXTRA_DATABASES
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_extra_database
          volumeMounts:
            - name: mongo-storage
              mountPath: /bitnami/mongodb
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
