apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo_root_user: cm9vdA==        # base64 of "root"
  mongo_root_password : ZXhhbXBsZQ==  # base64 of "example"
  mongo_1001_user: MTAwMQ==         # base64 of "1001"
  mongo_1001_password: MTAwMQ==         # base64 of "1001"
  mongo_1001_database: bXlkYg==         # base64 of "mydb"
  mongo_extra_user: bW9uZ28=  # base64 of "mongo"
  mongo_extra_password: bW9uZ28=  # base64 of "mongo"
  mongo_extra_database: bXlkYg==   # base64 of "mydb"
stringData:
  DATABASE_URI: "mongodb://mongo:mongo@mongo:27017/mydb?authSource=mydb"

