apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all your base resources
resources:
- ingress-deployment.yaml
- secret-deployment.yaml
#- pvc-deployment.yaml


# Common labels applied to all resources
#commonLabels:
 # project: expensy


