apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_ROOT_USER: cm9vdA==        # base64 of "root"
  MONGODB_ROOT_PASSWORD: ZXhhbXBsZQ==  # base64 of "example"
  MONGODB_USERNAME: MTAwMQ==         # base64 of "1001"
  MONGODB_PASSWORD: MTAwMQ==         # base64 of "1001"
  MONGODB_DATABASE: YWRtaW4=         # base64 of "admin"
  MONGODB_EXTRA_USERNAME: bW9uZ28=  # base64 of "mongo"
  MONGODB_EXTRA_PASSWORD: bW9uZ28=  # base64 of "mongo"
  MONGODB_EXTRA_DATABASE: bXlkYg==   # base64 of "mydb"