name: 'Deploy Project3'

on:
  push:
    branches: [ "main", "workflow_dispatch" ]

permissions:
  id-token: write
  contents: read

env:
  K8S_NAMESPACE: expensy
  IMAGE_TAG: ${{ github.sha }}    

jobs: 

  build-and-push:
     name: Build and Push Images
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build & push frontend app image
         uses: docker/build-push-action@v5
         with:
           context: ./expensy_frontend
           push: true
           tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:${{ env.IMAGE_TAG }}
             ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest

       - name: Build & push backend app image
         uses: docker/build-push-action@v5
         with:
           context: ./expensy_backend
           push: true
           tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:${{ env.IMAGE_TAG }}
             ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:latest

  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: oidc

      #  Install kubectl
      - name: Install kubectl
        run: az aks install-cli

      - name: Get AKS Credentials
        uses: azure/cli@v1
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az aks get-credentials \
              --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
              --name ${{ secrets.AKS_CLUSTER_NAME }} \
              --overwrite-existing



      #  Deploy / update Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k k8s/.

     